config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => "homes#top"
  get "home/about" => "homes#about"
  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
  
  get '/search' => 'search#search'
  

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:index, :show, :edit, :update]
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

    def search
        @model = params["search"]["model"]
        @content = params["search"]["content"]
        @method = params["search"]["method"]
        @records = search_for(@model,@content,@method) #@user@bookの情報が入っている
    end

    private

    def search_for(model,content,method)
        if model == 'user'
            if method == 'perfect_match' #完全一致
               User.where('name LIKE ?', '%'+content+'%') #モデル名.where('カラム名 LIKE?', 条件に合わせた中身)
            elsif method == 'forward_match' #前方一致
               User.where('name LIKE ?', '%'+content)
            elsif method == 'backward_match' #後方一致
               User.where('name LIKE ?', content+'%')
            elsif method == 'partial' #部分一致
               User.where('name LIKE ?', '%'+content+'%')
            end
        else
            if method == 'perfect_match'
               Book.where('title LIKE ?', '%'+content+'%')
            elsif method == 'forward_match'
               Book.where('title LIKE ?', '%'+content)
            elsif method == 'backward_match'
               Book.where('title LIKE ?', content+'%')
            elsif method == 'partial'
               Book.where('title LIKE ?', '%'+content+'%')
            end
        end
    end

end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_form.html.erb
<%= form_with url:"/search", method: :get, local: true do |f| %>
	<%= f.text_field 'search[content]' %>
	<%= f.select 'search[model]',options_for_select({"名前" => "name", "本" => "book"}) %>
	<%= f.select 'search[method]', "完全一致" => "perfect_match", "前方一致" => "forward_match", "後方一致" => "backward_match", "部分一致" => "partial" %>
	<%= f.submit '検索' %>
<% end %>

app/views/search/search.html.erb
<div class="body">
	<div class="container">
		<div class="row">
			<div class="col-10">
				<% if @model == "user" %>
					<h2>Users search for <%= @content %></h2>
					<table class="table table-hover table-inverse">
						<thead>
							<tr>
								<th>image</th>
								<th>name</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<% @records.each do |user| %>
									<td>
										<%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %>
									</td>
									<td><%= user.name %></td>
                  <td><%= link_to "Show", user_path(user.id) %></td>
								<% end %>
							</tr>
						</tbody>
					</table>
				<% else %>
				<h2>Books search for <%= @content %></h2>
				<table class="table table-hover table-inverse">
					<thead>
						<tr>
							<th></th>
							<th>Title</th>
							<th>Opinion</th>
						</tr>
					</thead>
					<tbody>
						<tr>
						<% @records.each do |book| %>
							<td>
								<%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %>
							</td>
							<td><%= book.title %></td>
							<td><%= book.body %></td>
							<td><%= link_to "show", book_path(book.id) %></td>
						<% end %>
						</tr>
					</tbody>
				</table>
				<% end %>
			</div>
		</div>
	</div>
</div>